version: '3.8'
services:
  app:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb+srv://root1:root1@notificationexcersice.ysuk3v2.mongodb.net/?retryWrites=true&w=majority&appName=NotificationExcersice

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
